on: pull_request

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/go-setup@v2
        with:
          go-version: '^1.17'
      - run: make lint

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/go-setup@v2
        with:
          go-version: '^1.17'
      - run: make test


